name = "mycare"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[vars]
VITE_ADMIN_URL = "https://mycare.pages.dev/"
VITE_CAREGIVER_URL = "https://mycare.pages.dev/caregiver/"

[[d1_databases]]
binding = "DB"
database_name = "mycarePrototypeRDBMS"
database_id = "1944c5c6-7c20-4425-be39-122bc98adc8a"