name = "hello-cf-app"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

# D1 database binding.
# After running `wrangler d1 create hello-cf-db`, copy the
# database_id it prints and paste it below.
[[d1_databases]]
binding = "DB"                # accessed in code as env.DB
database_name = "hello-cf-db"
database_id = "c719fe25-e607-4567-8455-ed556d23b534"
